package com.peace.dao;

import com.peace.dataobject.SequenceDo;

public interface SequenceDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Jul 04 09:11:23 CST 2021
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Jul 04 09:11:23 CST 2021
     */
    int insert(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Jul 04 09:11:23 CST 2021
     */
    int insertSelective(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Jul 04 09:11:23 CST 2021
     */
    SequenceDo selectByPrimaryKey(String name);

    //因为要加上锁的
    SequenceDo getSequenceByName(String Name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Jul 04 09:11:23 CST 2021
     */
    int updateByPrimaryKeySelective(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Jul 04 09:11:23 CST 2021
     */
    int updateByPrimaryKey(SequenceDo record);
}